# NOTE: Mock values added here for helm linter to pass. Actual values are set in main.tf
licensing_subscription_channel: v4.2
licensing_catalog_source_image: icr.io/cpopen/ibm-licensing-catalog@sha256:7a6822eddbbdaa62555b61e529f3f620fa42c0e5472d48eeefeeaeea00f9e939
licensing_namespace: ibm-licensing
licensing_catalog: ibm-licensing-catalog
licensing_operator: ibm-licensing-operator-app
licensing_operator_group: licensing-operatorgroup
openshift_source: openshift-marketplace
