# NOTE: Mock values added here for helm linter to pass. Actual values are set in main.tf
cert_manager_subscription_channel: v4.2
cert_manager_catalog_source_image: icr.io/cpopen/ibm-cert-manager-operator-catalog@sha256:d67b90ea57739794853674a4999beba00cd67a806174a00d397f55eebb1a76f4
cert_manager_namespace: ibm-cert-manager
cert_manager_catalog: ibm-cert-manager-catalog
cert_manager_operator: ibm-cert-manager-operator
cert_manager_operator_group: cert-manager-operatorgroup
openshift_source: openshift-marketplace
